## Домашнее задание: библиотека Numpy

In [100]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [101]:
def print_matrix(matrix):
    """
    Функция для красивого вывода матрицы
    matrix: list of lists --- матрица для вывода
    """
    for row in matrix:
        print(" ".join(f"{elem:.2f}" for elem in row))
    print()

In [102]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((10, 10))
b = np.random.sample((10, 10))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Вывод размерности (ранг) каждой матрицы
print("Размерность матрицы a:", a.ndim)  # Размерность (количество осей)
print("Размерность матрицы b:", b.ndim)

# Вывод формы каждой матрицы
print("Форма матрицы a:", a.shape)  # Форма (размеры по каждой оси)
print("Форма матрицы b:", b.shape)
# ========
print_matrix(a)
print_matrix(b)

Размерность матрицы a: 2
Размерность матрицы b: 2
Форма матрицы a: (10, 10)
Форма матрицы b: (10, 10)
0.56 0.09 0.08 0.15 0.88 0.54 0.80 0.72 0.55 0.49
0.65 0.30 0.66 0.50 0.60 0.81 0.17 0.78 0.87 0.77
0.71 0.93 0.26 0.27 0.48 0.27 0.30 0.32 0.39 0.32
0.88 0.91 0.90 0.18 0.50 0.29 0.39 0.49 0.65 0.25
0.38 0.44 0.74 0.26 0.38 0.86 0.46 0.15 0.67 0.68
0.73 0.92 0.76 0.95 0.73 0.87 0.21 0.24 0.92 0.76
0.93 0.16 0.13 0.98 0.91 0.42 0.18 0.23 0.49 0.32
0.86 0.10 0.89 0.62 0.50 0.68 0.54 0.29 0.56 0.56
0.11 0.36 0.18 0.70 0.65 0.93 0.59 0.05 0.52 0.91
0.57 0.29 0.21 0.56 0.00 0.05 0.70 0.22 0.91 0.54

0.12 0.60 0.28 0.71 0.63 0.79 0.52 0.54 0.01 0.74
0.41 0.37 0.71 0.86 0.95 0.61 0.69 0.64 0.22 0.91
0.49 0.96 0.90 0.06 0.91 0.00 0.61 0.48 0.70 0.09
0.28 0.36 0.86 0.35 0.76 0.30 0.92 0.68 0.37 0.35
0.15 0.85 0.11 0.66 0.04 0.96 0.08 0.89 0.06 0.72
0.02 0.52 0.18 0.90 0.18 0.83 0.51 0.90 0.38 0.51
0.58 0.74 0.17 0.75 0.88 0.87 0.04 0.56 0.70 0.79
1.00 0.32 0.12 0.30 0.55 0.02 0.96 0.99 0.15 0.

In [103]:
def mult(a, b):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy

    """
    # ========
    # Получаем размер матрицы (предполагается, что обе матрицы квадратные)
    size = len(a)

    # Инициализируем результирующую матрицу нулями
    # Создаем список списков, где каждая строка заполнена нулями
    c = [[0.0 for _ in range(size)] for _ in range(size)]

    # Перемножение матриц
    # Проходим по всем строкам первой матрицы
    for i in range(size):
        # Для каждой строки проходим по всем столбцам второй матрицы
        for j in range(size):
            # Вычисляем значение элемента [i][j] результирующей матрицы
            for k in range(size):
                # Умножаем соответствующие элементы и добавляем к текущему значению
                c[i][j] += a[i][k] * b[k][j]

    # ========
    # Возвращаем результирующую матрицу
    return c

# Пример вызова функции (замените a и b на ваши данные)
result = mult(a, b)
print_matrix(result)


2.46 3.17 1.43 2.76 2.32 2.80 1.88 3.81 1.39 2.91
3.14 3.92 2.68 2.99 3.16 2.68 3.04 4.72 1.82 2.94
1.89 2.56 1.91 2.56 2.61 2.36 2.11 3.06 1.12 2.62
2.59 3.50 2.47 2.95 3.45 2.65 2.73 3.80 1.73 3.02
2.38 3.42 2.40 2.63 2.78 2.45 2.16 3.67 1.81 2.26
3.12 4.48 3.59 3.78 4.00 3.47 3.54 5.21 2.18 3.41
1.72 2.91 1.97 2.63 2.35 2.73 2.30 3.53 1.14 2.53
2.47 3.80 2.62 2.78 3.20 2.73 2.61 3.98 1.93 2.61
2.25 3.27 2.37 2.74 2.49 2.72 1.99 3.83 1.63 2.36
2.40 2.60 1.91 2.07 2.63 1.85 1.79 2.87 1.48 1.90



In [104]:

def np_mult(a, b):
    """
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    # ========
    # Используем функцию dot для перемножения матриц
    c = np.dot(a, b)
    return c
    # ========

result2 = np_mult(a, b)
print_matrix(result2)

2.46 3.17 1.43 2.76 2.32 2.80 1.88 3.81 1.39 2.91
3.14 3.92 2.68 2.99 3.16 2.68 3.04 4.72 1.82 2.94
1.89 2.56 1.91 2.56 2.61 2.36 2.11 3.06 1.12 2.62
2.59 3.50 2.47 2.95 3.45 2.65 2.73 3.80 1.73 3.02
2.38 3.42 2.40 2.63 2.78 2.45 2.16 3.67 1.81 2.26
3.12 4.48 3.59 3.78 4.00 3.47 3.54 5.21 2.18 3.41
1.72 2.91 1.97 2.63 2.35 2.73 2.30 3.53 1.14 2.53
2.47 3.80 2.62 2.78 3.20 2.73 2.61 3.98 1.93 2.61
2.25 3.27 2.37 2.74 2.49 2.72 1.99 3.83 1.63 2.36
2.40 2.60 1.91 2.07 2.63 1.85 1.79 2.87 1.48 1.90



In [105]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 0 ns
Wall time: 998 μs


In [106]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [107]:
# проверим корректность
assert np.allclose(np.array(M1), M2)
print(np.allclose(np.array(M1), M2))

True


### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. 

Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. 

Засеките время работы, как это показано в заданиях выше.

In [108]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.01931087 0.09758735 0.10858442] [0.29130437 0.22841945 0.58777989]


In [109]:
def scalar_product(a, b):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    # ========
    # Инициализируем результат
    c = 0.0

    # Вычисляем скалярное произведение
    for i in range(len(a)):
        c += a[i] * b[i]

    return c
    # ========

print(scalar_product(a, b))

0.0917399285991927


In [110]:
def np_scalar_product(a,b):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    # ========
    # Используем функцию dot для вычисления скалярного произведения
    c = np.dot(a, b)

    return c
    # ========

print(scalar_product(a, b))

0.0917399285991927


In [111]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)
print(np.allclose(product_1, product_2))

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns
True


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [112]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
  # ========
  # Получаем элементы главной диагонали
    diagonal_elements = np.diag(a)

    # Отбираем четные элементы
    even_elements = diagonal_elements[diagonal_elements % 2 == 0]

    # Находим сумму четных элементов
    c = np.sum(even_elements)

    return c
  # ========

# Пример использования
matrix = np.array([[4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Вызываем функцию
result = np_diag_2k(matrix)

# Выводим результат
print("Исходная матрица:")
print(matrix)
print("\nСумма четных элементов диагонали:", result)

Исходная матрица:
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Сумма четных элементов диагонали: 24


In [113]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 5, 1, 4, 8],
       [8, 6, 2, 8, 5],
       [4, 4, 3, 5, 1],
       [6, 1, 8, 7, 6],
       [1, 1, 9, 4, 8]], dtype=int32)

In [114]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(14)

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [115]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    # ========
    # Используем функцию cumsum для вычисления кумулятивных сумм по строкам
    S = np.cumsum(A, axis=1)
    
    return S
    # ========

In [116]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=(2, 10**3))
print(A)
%time S2 = cumsum(A)

[[0.0484609  0.21015531 0.60562338 ... 0.41379706 0.48242161 0.9851978 ]
 [0.38288095 0.01890423 0.6025287  ... 0.66730321 0.52323013 0.72030977]]
CPU times: total: 0 ns
Wall time: 0 ns


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [117]:
from copy import copy
def np_transformation(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    # ========
    # Получаем количество строк и столбцов
    num_rows, num_cols = X.shape

    # Создаем массив для хранения результатов
    S = np.zeros((num_rows, num_cols * 2), dtype=X.dtype)

    for i in range(num_rows):
        # Исходная строка
        original_row = X[i]

        # Преобразование строки
        transformed_row = np.copy(original_row)  # Копируем строку для изменений
        transformed_row[1::2] = a  # Заменяем элементы с нечетными индексами на a
        transformed_row[0::2] = transformed_row[0::2] ** 3  # Возводим в куб элементы с четными индексами

        # Записываем в обратном порядке
        transformed_row = transformed_row[::-1]

        # Объединяем оригинальную и преобразованную строку
        S[i] = np.concatenate((original_row, transformed_row))

    return S
    # ========
    
X = np.array([[100, 200, 300, 400, 500],
              [1, 2, 3, 4, 5]])

# Выводим исходный массив
print("Исходный массив:")
print(X)

# Применяем функцию np_transformation
result = np_transformation(X, a=1)

# Выводим результат
print("\nПреобразованный массив:")
print(result)

Исходный массив:
[[100 200 300 400 500]
 [  1   2   3   4   5]]

Преобразованный массив:
[[      100       200       300       400       500 125000000         1
   27000000         1   1000000]
 [        1         2         3         4         5       125         1
         27         1         1]]


In [118]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: total: 0 ns
Wall time: 0 ns
